### PR TITLE
feat: Add semantic releases and IAM support

### PR DESCRIPTION
**Pull request by germanattanasio**

### CODE REVIEW

**Comment by Naktibalda** [comment]
I don't know what `semantic releases` mean in the name of this feature, but I think that this had to be a major release, because upgrading to 1.8.0 broke my bot which had `version_date` and not `version` in configuration.

> An error occured in the receive middleware:  Error: Argument error: version was not specified

**Comment by germanattanasio** [comment]
🤦‍♂️

**Comment by germanattanasio** [comment]
@Naktibalda I can put a fix. Is the problem in the middleware constructor?

**Comment by germanattanasio** [comment]
I opened a PR to fix the problem here first. @Naktibalda can you take a look?

**Pull request merged**
