### PR TITLE
Handle if the user sends a location

### PR DESCRIPTION
**Pull request by dlarouche**

### CODE REVIEW

**Comment by dlarouche** [comment]
Forgot to mention, this is for Facebook messenger when a user shares his location (via mobile)

**Comment by dgterry** [comment]
@dlarouche hi! would you mind providing a little bit of background information on the use case? Any information on:

- what you are doing from the user perspective in Facebook messenger when this problem/limitation occurs
- what happens in the app/middleware
- what you would like to have happen in the app/middleware

 would be helpful. Thanks!

**Comment by dlarouche** [comment]
@dgterry Hi Terry, I noticed when the user shares his location from his mobile on facebook messenger, the middleware seems to dismiss the message therefor not available on my app. I'm pretty new to coding but I was hoping to receive the message on my app when it's someone sharing a location.

This might not be the right approach, feel free to remove this PR!

**Comment by aarora91** [comment]
Thanks for the PR @dlarouche . Can you clarify:
- why the location shared message is being ignored? Is it because `message.text === undefined`? 
- I suppose you want to use `message.attachments`. How do you want to use it? Why can't you simply use the `watsonMiddleware.before` and `watsonMiddleware.after` functions to do what you want?

**Pull request closed without merging**
