### PR TITLE
Fixed storage overwrite problem

### PR DESCRIPTION
**Pull request by aarora91**
-changed readContext function signature.
-updateContext first reads the latest context and then either creates a new storage user object or, appends to existing.

CC @benbrown

### CODE REVIEW

**Comment by Naktibalda** [comment]
This patch was wrong,
readContext returns context only, so after update earlier properties of context become top level properties and new context is assigned to context properties.

```js
var firstContext = {
  "a": 1,
  "b": 2
};
var secondContext = {
  "c": 3,
  "d": 4
};
utils.updateContext(message.user, storage, {context: firstContext}, function (err, response) {
  utils.updateContext(message.user, storage, {context: secondContext}, function (err, response) {

  }
}
```

After 2 updates content of storage is 
```js
{
  "U2BLZSKFG": {
    "a": 1
    "b": 2
    "context": {
      "c": 3
      "d": 4
    }
    "id": "U2BLZSKFG"
  }
}
```

**Comment by Naktibalda** [comment]
It causes `TypeError: Converting circular structure to JSON"` https://github.com/watson-developer-cloud/botkit-middleware/issues/71#issuecomment-312506143

**Comment by peterswimm** [comment]
Care to submit a PR in this project too? @Naktibalda we can discuss here once you posted the changes you are proposing.

**Comment by Naktibalda** [comment]
My PR was submitted to this project.

**Pull request merged**
