### PR TITLE
Add another function to middleware for Conversation API calls

### PR DESCRIPTION
**Pull request by stevenoh93**
This reduces the number of calls made to Conversation by calling a new function in the middleware in the `hears` event handler. Also fixes issue #20

### CODE REVIEW

**Comment by germanattanasio** [comment]
@stevenoh93 There are 2 tests that are failing.
Can you also add one test to validate we don't break #20 in the future?

**Comment by benbrown** [comment]
I would encourage you to leave the receive middleware in place as an option for people who want to use it that way, and _additionally_ expose the interpret function.

**Comment by stevenoh93** [comment]
@germanattanasio The way #20 is being handled is through Botkit's `hears` event system. I'm not sure if it's possible to write automated tests for that, or even need to write one. Thoughts @benbrown?

**Comment by stevenoh93** [comment]
@benbrown just updated the PR to incorporate your comment. @germanattanasio what do you think about the necessity of the new test?

**Pull request merged**
